/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parsesql;

import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.DataFlavor;
import java.awt.datatransfer.StringSelection;
import java.awt.datatransfer.Transferable;

/**
 *
 * @author odin
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ta_principal = new javax.swing.JTextArea();
        btn_pegar = new javax.swing.JButton();
        btn_copiar = new javax.swing.JButton();
        btn_limpiar = new javax.swing.JButton();
        btn_reemplazar = new javax.swing.JButton();
        btn_magia = new javax.swing.JButton();
        jt_enter = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setMinimumSize(new java.awt.Dimension(561, 309));

        ta_principal.setBackground(new java.awt.Color(0, 32, 57));
        ta_principal.setColumns(20);
        ta_principal.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        ta_principal.setForeground(new java.awt.Color(0, 255, 102));
        ta_principal.setLineWrap(true);
        ta_principal.setRows(5);
        ta_principal.setTabSize(13);
        jScrollPane1.setViewportView(ta_principal);

        btn_pegar.setText("PEGAR");
        btn_pegar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pegarActionPerformed(evt);
            }
        });

        btn_copiar.setText("COPIAR");
        btn_copiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_copiarActionPerformed(evt);
            }
        });

        btn_limpiar.setText("LIMPIAR");
        btn_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiarActionPerformed(evt);
            }
        });

        btn_reemplazar.setText("REEMPLAZAR");
        btn_reemplazar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reemplazarActionPerformed(evt);
            }
        });

        btn_magia.setText("MAGIA");
        btn_magia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_magiaActionPerformed(evt);
            }
        });

        jt_enter.setBackground(new java.awt.Color(0, 0, 0));
        jt_enter.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        jt_enter.setForeground(new java.awt.Color(0, 204, 204));
        jt_enter.setText("15");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_reemplazar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_magia, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_copiar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_pegar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jt_enter, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 584, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_pegar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_limpiar)
                        .addComponent(btn_reemplazar)
                        .addComponent(btn_magia)
                        .addComponent(jt_enter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_copiar)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_copiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_copiarActionPerformed
        String texto = this.ta_principal.getText().trim();

        this.copiarAlPortapapeles(texto);
    }//GEN-LAST:event_btn_copiarActionPerformed

    private String insertarSaltos(String texto) {
        int veces = 0;
        int salto = Integer.parseInt(jt_enter.getText().trim());
        String resultado = "";
        if (salto < texto.length()) {
            for (int i = 0; i < texto.length(); i++) {
                resultado += texto.charAt(i);
                if (texto.charAt(i) == ',') {
                    veces++;
                    if (veces == salto && texto.length() - 1 > i) {
                        veces = 0;
                        resultado += "\n";
                    }
                }
            }
            return resultado;
        } else {
            return texto;
        }

    }
    private void btn_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_btn_limpiarActionPerformed

    private void btn_pegarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pegarActionPerformed
        pegarDesdePortapapeles();
    }//GEN-LAST:event_btn_pegarActionPerformed

    private void btn_reemplazarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reemplazarActionPerformed
        reemplazar();
    }//GEN-LAST:event_btn_reemplazarActionPerformed

    private void reemplazar() {
        String texto = ta_principal.getText().trim().replace('"', '\'').replace('\n', ',');
        if (texto.endsWith(",")) {
            texto = texto.substring(0, texto.length() - 1);
        }
        this.ta_principal.setText(insertarSaltos(texto));
    }
    private void btn_magiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_magiaActionPerformed
        pegarDesdePortapapeles();
        reemplazar();
        copiarAlPortapapeles(ta_principal.getText());
    }//GEN-LAST:event_btn_magiaActionPerformed

    private void limpiar() {
        this.ta_principal.setText("");
    }

    private void pegarDesdePortapapeles() {
        Clipboard c = Toolkit.getDefaultToolkit().getSystemClipboard();
        Transferable t = c.getContents(this);
        if (t == null) {
            return;
        }
        try {
            ta_principal.setText((String) t.getTransferData(DataFlavor.stringFlavor));
        } catch (Exception e) {
            this.ta_principal.setText(e.getMessage());
        }
    }

    private void copiarAlPortapapeles(String s) {
        StringSelection stringSelection = new StringSelection(s);
        Clipboard clpbrd = Toolkit.getDefaultToolkit().getSystemClipboard();
        clpbrd.setContents(stringSelection, null);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Main m = new Main();
                m.setLocationRelativeTo(null);
                m.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_copiar;
    private javax.swing.JButton btn_limpiar;
    private javax.swing.JButton btn_magia;
    private javax.swing.JButton btn_pegar;
    private javax.swing.JButton btn_reemplazar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jt_enter;
    private javax.swing.JTextArea ta_principal;
    // End of variables declaration//GEN-END:variables
}
